services:
  flights-api:
    build:
      context: .
      dockerfile: Dockerfile_go
    container_name: flights-api
    networks:
      - flights-net
    ports:
      - "8081:8080"
    restart: unless-stopped

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile_py
    container_name: dashboard
    networks:
      - flights-net
    ports:
      - "${DASHBOARD_PORT:-8080}:8080"
    environment:
      - API_BASE_URL=http://flights-api:8080
    depends_on:
      - flights-api
    restart: unless-stopped

networks:
  flights-net:
    driver: bridge
